# Generated by Django 5.2.11 on 2026-07-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('rango', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('serie', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('frecuencia_control', models.IntegerField(blank=True, null=True)),
                ('ultima_calibracion', models.DateField(blank=True, null=True)),
                ('vencimiento_calibracion', models.DateField(blank=True, null=True)),
                ('num_certificado', models.CharField(blank=True, max_length=100, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(default='APTO', max_length=50)),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
