# Generated by Django 5.2.11 on 2026-07-29 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrologia', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='metrologia.instrumento')),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='personal.operario')),
            ],
        ),
    ]
