# Generated by Django 5.2.11 on 2026-08-03 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrologia', '0002_prestamo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCalibracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_calibracion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('num_certificado', models.CharField(blank=True, max_length=100, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibraciones', to='metrologia.instrumento')),
            ],
        ),
    ]
