# Generated by Django 5.2.11 on 2026-09-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrologia', '0003_historialcalibracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_days_threshold', models.IntegerField(default=45)),
                ('company_name', models.CharField(default='ABBAMAT', max_length=255)),
                ('plant_name', models.CharField(default='Planta Principal', max_length=255)),
                ('default_calibration_interval_months', models.IntegerField(default=12)),
            ],
        ),
    ]
