# Generated by Django 5.2.11 on 2026-09-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrologia', '0004_systemconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='ruta_pdf',
            field=models.TextField(blank=True, null=True),
        ),
    ]
