# Generated by Django 5.2.11 on 2026-09-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrologia', '0005_instrumento_ruta_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='default_calibration_interval_months',
        ),
    ]
