# Generated by Django 5.2.11 on 2026-09-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrologia', '0006_remove_systemconfiguration_default_calibration_interval_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='reports_base_path',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
