# Generated by Django 5.2.11 on 2026-09-22 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrologia', '0007_systemconfiguration_reports_base_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pasillo', models.CharField(blank=True, max_length=50, null=True)),
                ('estante', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='instrumento',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrumentos', to='metrologia.ubicacion'),
        ),
    ]
