# Generated by Django 5.2.11 on 2026-09-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrologia', '0009_instrumentauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
    ]
